### ISSUE TITLE
<filename/>, <screen/> and the like are printed but should be blocked

### ISSUE THREAD

**Issue by tbazant** [openSUSE/vscode-suse-vale-styleguide#18]
![obrazek](https://github.com/openSUSE/vscode-suse-vale-styleguide/assets/2240174/6c688c08-6b80-4975-b303-697bc3faf5d2)

it seems that the whole block
![obrazek](https://github.com/openSUSE/vscode-suse-vale-styleguide/assets/2240174/8839a77e-830c-4717-8d22-389c666a5744)
is not taken into account

**Comment by tomschr** [comment]
Hi @tbazant,

that is true, the template matches for these elements and they are ignored. That's on purpose. Usually you don't want to (spell)check a command or an option. The content of these elements contains also some markup that can confuse your spell checker.

**Comment by tomschr** [comment]
I also tried to reproduce your scenario. I used the file `ulp.xml` from the doc-sle main branch. This file contains some `<screen>`s and `--` characters:

```
$ grep "\-\-[a-zA-Z]" xml/ulp.xml
          live patch by using the <option>--revert</option> switch and passing
<screen>&prompt.user;ulp trigger -p <replaceable>PID</replaceable> --revert <replaceable>LIVEPATCH</replaceable>.so</screen>
<screen>&prompt.user;ulp trigger -p <replaceable>PID</replaceable> --revert-all=<replaceable>LIBRARY</replaceable></screen>
<screen>&prompt.user;ulp trigger -p <replaceable>PID</replaceable>  --revert-all=libcrypto.so.1.1 new_livepatch2.so</screen>
```

If I call the stylesheet, the result does NOT contain the `<option>`:

```
$ xsltproc xslt/vale-docbook.xsl ~/repos/GH/SUSE/doc-sle/xml/ulp.xml 2>/dev/null | grep "live patch by using"
          live patch by using the  switch and passing
```

**Comment by tbazant** [comment]
problem was a bad symlink in my docbook-xsl setup
