### ISSUE TITLE
Fix Termweb for SD

### ISSUE THREAD

**Issue by tbazant** [openSUSE/vscode-suse-vale-styleguide#25]
![obrazek](https://github.com/openSUSE/vscode-suse-vale-styleguide/assets/2240174/2fc36ddc-648d-499e-b7e3-739e6fc9d6c8)

**Comment by tbazant** [comment]
@jfaltenbacher  can you please update the term `solid-state drive` and insert a regexp `(?<!\S)sd` for `sd` and `(?<!\S)SD` for `SD`?

**Comment by tbazant** [comment]
fixed by https://github.com/openSUSE/vscode-suse-vale-styleguide/commit/6728802912cdfc9d99028230e6f7382eaf3a2255

**Comment by jfaltenbacher** [comment]
regex added to TermWeb as requested
