### ISSUE TITLE
Conflicting rules for serial comma

### ISSUE THREAD

**Issue by sounix000** [openSUSE/vscode-suse-vale-styleguide#3]
The SerialComma.yml rule for Oxford serial comma, and the SimpleSeries.yml rule seems to offer conflicting suggestions about using comma. At least that is my experience when using the Vale extension for VS Code.

A duplicate of this issue is here: https://github.com/openSUSE/suse-vale-styleguide/issues/62#issue-1798884152. Please close one of them, as appropriate.

**Comment by tbazant** [comment]
SerialComma.yml was removed in the last update
